### ISSUE TITLE
The sources of an image

### ISSUE THREAD

**Issue by Sugydro** [lndgalante/archillect-unoffcial-api#1]
Hello. Can you also add a retrieving the sources of an image? 

So it should look like this:

GET https://archillect-api.now.sh/visuals/147836
```json
{
  "source": "http://78.media.tumblr.com/a06af535eb801c32ff60c5dbb0031d13/tumblr_olhnlsSjnS1vczpxxo1_400.gif",
  "original": "http://archillect.com/147836",
  "id": 147836,
  "sourceLinks": [
  "http://domain.com",
  "http://example.org"
  ]
}

**Comment by lndgalante** [comment]
Hi @Sugydro 👋 thanks for the issue! 

Check same link https://archillect-api.now.sh/visuals/147836

Let me know if you find any problem or want to request any additional feature.

**Comment by Sugydro** [comment]
**sourceLinks** returns **&#8465;** instead of **&**, can you fix it, please?

**Comment by lndgalante** [comment]
Sure @Sugydro let me find a solution

**Comment by Sugydro** [comment]
It seems that this applies only to the Google search link.

**Comment by lndgalante** [comment]
I re-opened the issue until we fixed it. Thanks for the info

**Comment by lndgalante** [comment]
@Sugydro fixed! Any other bug just send me an issue.  Thanks!
