### ISSUE TITLE
Caching system errors and caching time suggestions.

### ISSUE THREAD

**Issue by Sugydro** [lndgalante/archillect-unoffcial-api#2]
Hello. Caching for 24 hours is too long, especially for retrieving the last and random image. 

So, I suggest the following limits.
> 24 hours or more, because the data of specified image will not change:
> - `https://archillect-api.now.sh/visuals/{id}`

> To get actual data the caching time of these ones should be within 10 minutes. The less the better.
> 
> - `https://archillect-api.now.sh/visuals`
> - `https://archillect-api.now.sh/visuals?per={count}`
> - `https://archillect-api.now.sh/random`

And getting the last image id is not working now: https://archillect-api.now.sh/visuals?per=1

**Comment by lndgalante** [comment]
@Sugydro thanks to #3 this issue is fixed now.
